### ISSUE TITLE
希望提供更简便的设定绕行模式的方法

### ISSUE THREAD

**Issue by kanshurichard** [Asterisk4Magisk/Xray4Magisk#15]
如GUI工具是最好的。

如果没有GUI工具，希望可以把目前用appid识别的方法改成识别包名。

因为诸如v2rayNG这样的APP，可以一次性导出包名用作填充配置文件。

**Comment by whalechoi** [comment]
~~GUI在做了，进度mkdir~~

**Comment by whalechoi** [comment]
[欢迎试用](https://github.com/whalechoi/Xray4Magisk_Manager/releases)

**Comment by whalechoi** [comment]
~~gui弃坑了~~，可以试试golang版本

**Comment by tsaiajie** [comment]
> ~gui弃坑了~，可以试试golang版本

虽然看不懂 但是大佬还是很厉害的 摸摸大佬
