### ISSUE TITLE
移动网下应该默认禁用v6

### ISSUE THREAD

**Issue by bigjunda** [Asterisk4Magisk/Xray4Magisk#25]

**Comment by CerteKim** [comment]
本模块默认禁用 v6
脚本难以检测当前所处环境是否为移动网络，建议手动处理。

**Comment by bigjunda** [comment]
使用ip111检测时候还是有个别情况出现v6地址，目前只能使用APN禁用v6

**Comment by CerteKim** [comment]
可能是通过 proxy 的那部分有 v6 吧。。可以详细描述下吗

**Comment by bigjunda** [comment]
代理服务器是纯v4服务器. 检测出来的v6为国内移动网络v6地址

**Comment by CerteKim** [comment]
理论上不应该会检测到 v6，目前模块默认的 freedom outbound 的 domainStrategy 为 UseIPv4。（之前是 UseIP）
建议检查一下。

**Comment by CerteKim** [comment]
Android 处理 SIM 卡网络比较复杂，说实话也不是很清楚 Android 的 netd 要怎么用。

**Comment by bigjunda** [comment]
是偶发性的，不是每次使用代理都会检测到ipv6地址

**Comment by CerteKim** [comment]
嗯。。奇怪。。我这还没遇到过这种现象。
实在不行的话，把 freedom 的 socketOpt 的 domainStrategy 改成 UseIPv4 吧
