### ISSUE TITLE
关闭服务时强制重启网络

### ISSUE THREAD

**Issue by ikdataa** [Asterisk4Magisk/Xray4Magisk#42]
关闭服务会重启网络，而且是两次
`/data/adb/xray/scripts/xray.tproxy disable&&/data/adb/xray/scripts/xray.service stop`
希望加个开关，让用户决定关闭服务时是否重启网络

**Comment by CerteKim** [comment]
本模块的重启网络是由 xray.inotify 触发，只有当在 Magisk Manager 中重新开启模块才会导致出现。
所以可能并不是模块问题，建议详细测试。

关于那个“是否重启网络”的开关：
很多时候重启网络（本质上是开启，再关闭一次飞行模式）是必要的，这是目前唯一能够清除 Android DNS 缓存的方法。
且自动重启网络这项功能在 Android 7.0 + 已经不再能够使用。
