### ISSUE TITLE
無法安裝

### ISSUE THREAD

**Issue by cskmaband** [Asterisk4Magisk/Xray4Magisk#44]
安裝的時候說缺少crul或是wget ，請問有什麼方法解決？

**Comment by CerteKim** [comment]
可以尝试安装 Magisk 官方仓库的 Busybox 模块，重启手机之后再次安装 Xray4Magisk。
或者直接使用手动下载的方法。

**Comment by cskmaband** [comment]
> 可以尝试安装 Magisk 官方仓库的 Busybox 模块，重启手机之后再次安装 Xray4Magisk。
> 或者直接使用手动下载的方法。

好的，我去試試
