### ISSUE TITLE
每次启动，service.log内都会出现同样的No such file or directory记录

### ISSUE THREAD

**Issue by Aniark** [Asterisk4Magisk/Xray4Magisk#46]
记录如下
probing proxy mode
[Info]: Starting xray service.
rollback route settings
RTNETLINK answers: No such file or directory
disable ipv4 proxy
[Info]: cleaning mangle iptables
/data/adb/xray/scripts/xray.tproxy[260]: can't create /proc/sys/net/ipv6/conf/wlan0/accept_ra: No such file or directory
/data/adb/xray/scripts/xray.tproxy[260]: can't create /proc/sys/net/ipv6/conf/wlan0/disable_ipv6: No such file or directory
probing proxy mode
apply route settings
enable ipv4 proxy
[Info]: creating mangle chain
[Info]: creating proxy
/data/adb/xray/scripts/xray.tproxy[260]: can't create /proc/sys/net/ipv6/conf/wlan0/accept_ra: No such file or directory
/data/adb/xray/scripts/xray.tproxy[260]: can't create /proc/sys/net/ipv6/conf/wlan0/disable_ipv6: No such file or directory
[Info]: xray service is running. ( PID: 24549 )

**Comment by CerteKim** [comment]
为了保证可靠，每次启动都会清理一次 ip rule、ip route 以及 iptables 的规则；当启动之前这些规则并不存在时，日志出现 No such file ordirectory 是正常现象。
