### ISSUE TITLE
开启热点共享时，连接的客户端无网络

### ISSUE THREAD

**Issue by xcxnig** [Asterisk4Magisk/Xray4Magisk#49]
使用环境：

Android: 10
Magisk: v23.0(23000)
Magisk App: v23.0(23000)(21)
Xray4Magisk: Module v1.5.0, Core v1.4.2

- [✔] DNS解析域名正常
- [✖] TCP连接失败
- [✔] ICMP Ping正常

配置文件：
> pwd
>>`/data/adb/xray`

> cat ap.list
>>`wlan1`
`rndis0`

> cat ignore_out.list
>>`wlan0`

> ip addr
>>`22: wlan1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 3000`
`    link/ether 72:31:5f:3f:a2:b8 brd ff:ff:ff:ff:ff:ff`
`    inet 192.168.43.1/24 brd 192.168.43.255 scope global wlan1`
`       valid_lft forever preferred_lft forever`
`    inet6 fe80::7031:5fff:fe3f:a2b8/64 scope link`
`       valid_lft forever preferred_lft forever`

>>`29: rndis0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000`
`    link/ether 32:17:54:fd:c5:88 brd ff:ff:ff:ff:ff:ff`
`    inet 192.168.42.129/24 brd 192.168.42.255 scope global rndis0`
`       valid_lft forever preferred_lft forever`
`    inet6 fe80::3017:54ff:fefd:c588/64 scope link`
`       valid_lft forever preferred_lft forever`

**Comment by CerteKim** [comment]
看看 `iptables -t mangle -S` 的输出

**Comment by xcxnig** [comment]
内容过长 已粘贴至 [Ubuntu Pastebin](https://pastebin.ubuntu.com/p/PtjYsHG7gZ/)

**Comment by xcxnig** [comment]
wlan1:  WIFI热点 
rndis0: USB网络共享
bt-pan: 蓝牙网络共享

**Comment by CerteKim** [comment]
检查一下 base.json 中 proxy-in（dokodemo-door）listen。

**Comment by xcxnig** [comment]
base.json

```json
"inbounds": [
    {
      "tag": "proxy-in",
      "listen": "127.0.0.1",
      "port": 65535,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "udp,tcp",
        "followRedirect": true
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy"
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ]
```
当 `"listen": "127.0.0.1"` 设置为 `"listen": "0.0.0.0"` 时，所有热点功能正常。

**Comment by xcxnig** [comment]
奇怪的 bug 增加了

`"listen": "0.0.0.0"` 时，SafetyNet无法正常通过测试

关闭模块时，SafetyNet测试正常
![关闭模块时，SafetyNet测试正常](https://i.loli.net/2021/08/02/zwDvdMbNkoC1nY6.jpg)
开启模块时，SafetyNet测试失败
![开启模块时，SafetyNet测试失败](https://i.loli.net/2021/08/02/8Q7KDZ5Nu6WbHX2.jpg )
SafetyNet Fail (Can't access Google Play Services
![SafetyNet Fail (Can't access Google Play Services](https://i.loli.net/2021/08/02/BFdolTD8kZLKSIJ.jpg )

**Comment by CerteKim** [comment]
确实很奇怪，我这里没有出现这种情况

**Comment by CerteKim** [comment]
如果开了 ipv6 代理的话，listen整一行删掉监听双栈地址。

**Comment by Aniark** [comment]
> 奇怪的 bug 增加了
> 
> `"listen": "0.0.0.0"` 时，SafetyNet无法正常通过测试
> 
> 关闭模块时，SafetyNet测试正常

试一试使用[这个模块](https://github.com/kdrag0n/safetynet-fix) 来通过safetynet测试，记得打开magisk hide

**Comment by xcxnig** [comment]
关闭Xray4Magisk后测试可以正常通过，仅当监听0.0.0.0时SafetyNet出现异常，MIUI系统给出的网络诊断结果为`本地环回测试失败`
![本地环回测试失败](https://i.loli.net/2021/08/03/7FRNMGkYDj43Lmv.jpg)

**Comment by CerteKim** [comment]
appid 是如何配置的

**Comment by xcxnig** [comment]
ALL

**Comment by CerteKim** [comment]
在 appid 里面加上

```
bypass
3003
3004
```

试试

**Comment by xcxnig** [comment]
> 在 appid 里面加上
> 
> ```
> bypass
> 3003
> 3004
> ```
> 
> 试试

这个并没有效果。
我查看了一下系统进程，并没有PID为3003/3004的进程
附上手机进程列表 [https://paste.ubuntu.com/p/Jkf6q7mZPp/
](https://paste.ubuntu.com/p/Jkf6q7mZPp/
)

**Comment by CerteKim** [comment]
这个不是 pid，是 uid。。不过不能用的话确实也挺奇怪的。。。

使用旧版本的 Xray4Magisk 是否也有这个情况

**Comment by xcxnig** [comment]
经过多次测试后好像发现问题了，应该是DNS污染导致的。通过iptables劫持DNS到1.1.1.1后问题不再出现

**Comment by CerteKim** [comment]
不必劫持的。。
可能是 dns 模块配置错误了

**Comment by xcxnig** [comment]
目前修改为 如下配置 使用正常。

```json
{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com",
      "domain:google.cn": "google.com"
    },
    "servers": [
        "https+local://223.5.5.5/dns-query",
        {
            "address": "https://dns.pub/dns-query",
            "domains": [
                "geosite:cn"
            ]
        },
        {
            "address": "https://1.1.1.1/dns-query",
            "domains": [
                "geosite:geolocation-!cn"
            ]
        }
    ],
    "queryStrategy": "UseIPv4",
    "disableCache": true,
    "disableFallback": true,
    "tag": "dns"
  }
}

```
