### ISSUE TITLE
无法启动xray

### ISSUE THREAD

**Issue by wfniub** [Asterisk4Magisk/Xray4Magisk#56]
Andy:
[Info]: Starting xray service.
[Error]: Start xray service Failed.

Andy:
[Info]: Starting xray service.
grep: /proc/12125/cmdline: No such file or directory
[Error]: Start xray service Failed.
inotifyd: exec /data/adb/xray/scripts/xray.inotify: Permission denied
inotifyd: exec /data/adb/xray/scripts/xray.inotify: Permission denied
inotifyd: exec /data/adb/xray/scripts/xray.inotify: Permission denied
inotifyd: exec /data/adb/xray/scripts/xray.inotify: Permission denied
inotifyd: exec /data/adb/xray/scripts/xray.inotify: Permission denied
inotifyd: exec /data/adb/xray/scripts/xray.inotify: Permission denied
inotifyd: exec /data/adb/xray/scripts/xray.inotify: Permission denied

安装模块后看日志是这个，不知道咋回事！

**Comment by CerteKim** [comment]
检查一下 error.log
