### ISSUE TITLE
启用 fakedns 后，路由无法如期直连被解析为内网 ip 的域名

### ISSUE THREAD

**Issue by Aniark** [Asterisk4Magisk/Xray4Magisk#57]
路由已配置 geoip:private 直连，域名策略为 IPIfNonMatch ，但在访问诸如 imis.qq.com 之类的被解析为 127.0.0.1 的网址时，未能如期直连

虽然可以通过手动添加域名规则到路由表里实现直连，但考虑到类似的域名颇多，还是解析为 ip 再连接更一劳永逸

**Comment by CerteKim** [comment]
fakedns 应该也可以像 routing 一样配置
```
"domain": [

]
```

**Comment by Aniark** [comment]
不足以从根本上解决问题

题外话：release 1.5.2 似乎没改版本号，magisk 内显示版本号为 1.5.1

**Comment by CerteKim** [comment]
可能得去 xray 那边问问了。

1.5.2 那个确实忘记改了谢谢提醒

**Comment by Aniark** [comment]
测试了一下1.5.2和1.5.3，均为 wifi 下能正常直连，数据网络则不行
