### ISSUE TITLE
Pandora无法使用

### ISSUE THREAD

**Issue by soundghost** [Asterisk4Magisk/Xray4Magisk#66]
Pandora（收音机）无法使用，提示未在你的国家提供服务。
使用Xray4Magisk_Manager强制Pandora走Proxy却又只能进入软件，能看到界面和列表，但是点播放无法播放（且进入界面缓慢）。
同样的配置在PC端是可以用Pandora的。

**Comment by CerteKim** [comment]
@soundghost 可能需要修改一下dns

**Comment by soundghost** [comment]
谢谢回复。

我尝试学习一下。
