### ISSUE TITLE
双卡手机，使用卡2(sim2)的网络流量时开启Xray4Magisk会断网

### ISSUE THREAD

**Issue by simplerick-simplefun** [Asterisk4Magisk/Xray4Magisk#72]
双卡手机，使用卡2(sim 2)的网络流量时开启Xray4Magisk会导致断网，表现为无法连接互联网，打不开网页等。

测试手机：
1加7 pro
红米 K50

怀疑是iptable的设置问题，但是我不太懂这一块。

**Comment by CerteKim** [comment]
@simplerick-simplefun 目前没有好的办法来规避这个问题，出现问题时建议重新启动 x4m，或者重新启用网络。

**Comment by simplerick-simplefun** [comment]
> @simplerick-simplefun 目前没有好的办法来规避这个问题，出现问题时建议重新启动 x4m，或者重新启用网络。

这个我试了几遍，跟切换网络/重启网络没有关系，就是sim卡2的网络无法与Xray4Magisk同时使用。
确定没办法就close了。
