### ISSUE TITLE
红米K50，MIUI 13，京东淘宝等app无法加载图片

### ISSUE THREAD

**Issue by simplerick-simplefun** [Asterisk4Magisk/Xray4Magisk#75]
碰到了一个奇怪的问题。我之前用一加7pro都没问题。
最近换了红米K50，使用MIUI 13稳定版。
我研究了一下了，可能跟使用联发科天玑8100有关。相关的网络device列表跟高通的也不一样。

开了[Xray4Magisk]后，不管全局代理也好，黑白名单也好，单个app走不走代理，总是会有一些特定的app里面一些连接无法加载。
比如京东、淘宝，商品图片就无法加载，但是商品详情部分的图片就可以加载。起点读书，也有类似的问题，有些内容会无法加载。

请问有没有什么办法，可以追踪这些连接的数据包走的是哪一个device，走了哪些table/rules，导致加载不出来？

**Comment by simplerick-simplefun** [comment]
找到问题和解决方案了。首先，注意到上述问题只出现在wifi连接时，用手机流量连接网络时就是正常的。
于是我研究了一下，把tproxy那里AP的部分comment掉了
https://github.com/Asterisk4Magisk/Xray4Magisk/blob/856d5adbd342e52aae7843a75efda0bf3af8eb29/xray/scripts/xray.tproxy#L137-L140
我手机上无线网的连接device是wlan0，xray ap里面的设置是wlan+，这样相当于去掉了无线网xray端口的转发。具体为什么还没想明白。

**Comment by oswicer** [comment]
也许和cpu没关系，因为我是K50至尊版（高通的芯片），用了两个月以后也出现这个问题了，不过你的临时解决方案的确可行，改成流量就可以正常加载图片了，非常感谢
