### ISSUE TITLE
错误 iptables v1.4.11.1: unknown option "-w" 是不是android4.4太老了？

### ISSUE THREAD

**Issue by zanjie1999** [Asterisk4Magisk/Xray4Magisk#87]
想把这装在随身wifi上实现透明代理
系统是android4.4
uname -a
Linux localhost 3.10.28 #1 SMP PREEMPT Thu Aug 18 16:06:48 CST 2022 armv7l GNU/Linux
启动后 cat run/service.log 内有大量
```
iptables v1.4.11.1: unknown option "-w"
Try `iptables -h' or 'iptables --help' for more information
```
看起来规则并没有生效，有没有什么办法补救一下（
sp970 v13的debian不配拥有modem驱动

**Comment by CerteKim** [comment]
可以把腳本裡面 -w 的參數刪掉
