### ISSUE TITLE
[HELP] "Cannot find your tun device xtun"

### ISSUE THREAD

**Issue by Anderhar** [Asterisk4Magisk/Xray4Magisk#92]
Greetings!

I'm hoping to utilize this Magisk module instead of traditional GUI clients to avoid occupying system VPN in scenarios where it's necessary to tunnel selected apps without proxy support. As far as I understand, this is accomplished by using TUN mode in combination with Sing-Box core (because Xray doesn't support TUN). Unfortunately, when I try to deploy this configuration referring to example configs ([1](https://github.com/simplerick-simplefun/Xray4Magisk/blob/x4m-plugin/xray/etc/confs/sing-box-tun-config-example.json)&[2](https://github.com/chika0801/sing-box-examples/blob/main/Tun/config_client_android_self-use.json)), the `xrayhelper proxy refresh` command always results in the following output:

`ERROR : [tun] XrayHelper/main/proxies/tun: cannot find your tun device xtun did you configure core correctly? ` 

I would greatly appreciate being pointed out to my oversight and, if possible, for some detailed instructions regarding TUN (because these are just my baby steps in learning proxy tools of this type).

**Comment by tsaiajie** [comment]
Xray4Magisk three modes tproxy, tun, tun2socks, all can do not occupy the system VPN
Xray can use tproxy, tun2socks, tun will be added in version 1.9.
You can use tproxy, he is the default mode of Xray4Magisk, just need to directly on the default configuration to change some parameters to your can be used!

**Comment by CerteKim** [comment]
You may need to add `"interface_name": "tun0",` in sing-box's tun configuration
