### ISSUE TITLE
【BUG】配置文件proxy.json生成不全

### ISSUE THREAD

**Issue by powerAn2020** [Asterisk4Magisk/Xray4Magisk#94]
1. xray-core 下使用xrayhelper 命令切换节点时生成的文件中streamSettings.tcpSettings缺失，导致无法正常联网
2. xrayhelper switch 命令列表里中文没转换完全
![list](https://github.com/Asterisk4Magisk/Xray4Magisk/assets/25736019/00a4d192-8480-455e-a0ce-c590092d0342)

**Comment by whalechoi** [comment]
https://github.com/Asterisk4Magisk/XrayHelper/issues/13
