### ISSUE TITLE
webui blank 

### ISSUE THREAD

**Issue by trialman** [Asterisk4Magisk/Xray4Magisk#96]
web ui shows nothing .  ZygiskNext UI works fine
![image](https://github.com/Asterisk4Magisk/Xray4Magisk/assets/5611750/11498e93-f254-4328-85ee-c5ba5c2d969e)

kernelSU version : 1.0 
Xray4Magisk: v3.3.4
Kernel: sing-box

**Comment by whalechoi** [comment]
Enable webview debug in kernelsu manager, and follow this https://developer.chrome.com/docs/devtools/remote-debugging/webviews.

Is console get any error?

**Comment by trialman** [comment]
yes , json parse error
![image](https://github.com/Asterisk4Magisk/Xray4Magisk/assets/5611750/dec5e322-f976-471b-a0f4-24bc72c83b9b)

**Comment by trialman** [comment]
close the webui than reopen it ,  it shows blank again!

**Comment by whalechoi** [comment]
Hi, I reupload v3.3.4 with this commit [xray4magisk-ksu-webui#6d5bcbe](https://github.com/Asterisk4Magisk/xray4magisk-ksu-webui/commit/6d5bcbe77b8953bf52ce5606659e3fe68d765644) to fix this, but maybe you need clear localStorage again.

**Comment by trialman** [comment]
> Hi, I reupload v3.3.4 with this commit [xray4magisk-ksu-webui#6d5bcbe](https://github.com/Asterisk4Magisk/xray4magisk-ksu-webui/commit/6d5bcbe77b8953bf52ce5606659e3fe68d765644) to fix this, but maybe you need clear localStorage again.
the new version works fine !
