### ISSUE TITLE
Inbound/Routing/DNS management

### ISSUE THREAD

**Issue by diecko69** [Asterisk4Magisk/Xray4Magisk#98]
I am writing to suggest the implementation of a routing management feature in XrayHelper. This feature would significantly improve the user experience by providing greater control and customization options.

I appreciate your attention to this matter and your ongoing commitment to enhancing the software.

Thank you for your consideration.

**Comment by whalechoi** [comment]
https://github.com/Asterisk4Magisk/Xray4Magisk/releases/tag/v3.4.6
